<?php  ?>
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
	<div class="mdl-card__title mdl-color--primary mdl-color-text--white">
		<h2 class="mdl-card__title-text">Register</h2>
	</div>
	<div class="mdl-card__supporting-text">
	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'register-form',
		'enableAjaxValidation'=>true,
	)); ?>
	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
		<input class="mdl-textfield__input" type="text" id="username" value="<?php echo $model->username ?>" readonly="true" name="FpaUser[username]" />
		<label class="mdl-textfield__label" for="username">Username (Generated By Sistem)</label>
		<?php echo $form->error($model, 'username'); ?>
	</div>
	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
		<input class="mdl-textfield__input" type="password" id="userpass" name="FpaUser[password]" />
		<label class="mdl-textfield__label" for="userpass">Password</label>
		<?php echo $form->error($model, 'password'); ?>
	</div>
	</div>
	<div class="mdl-card__actions mdl-card--border">
		<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit">Register</button>
		<a href="<?php echo Yii::app()->createUrl('login') ?>" class="mdl-button mdl-js-button mdl-js-ripple-effect">Cancel</a>
	</div>
	<?php $this->endWidget(); ?>
</div>


